apps/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='IndexView'),
    url(r'^cbv/form1/$', views.Form1View.as_view(), name='Form1View'),
    url(r'^fbv/form1/$', views.form1_view, name='form1_view'),
    url(r'^success/$', views.SuccessView.as_view(), name='SuccessView'),

    url(r'^item/(?P<pk>[^/]+)/$', views.ItemDetailView.as_view(),
        name='ItemDetailView'),

    url(r'^cbv/item/create/$', views.ItemCreateUpdateView.as_view(),
        name='ItemCreateView'),
    url(r'^cbv/item/update/(?P<pk>[^/]+)/$',
        views.ItemCreateUpdateView.as_view(),
        name='ItemUpdateView'),

    url(r'^ajax/cbv/item/create/$', views.ItemCreateUpdateViewAjax.as_view(),
        name='ItemCreateViewAjax'),
    url(r'^ajax/cbv/item/update/(?P<pk>[^/]+)/$',
        views.ItemCreateUpdateViewAjax.as_view(),
        name='ItemUpdateViewAjax'),

    url(r'^fbv/item/create/$', views.item_create_update_view,
        name='item_create_view'),
    url(r'^fbv/item/update/(?P<pk>[^/]+)/$', views.item_create_update_view,
        name='item_update_view'),
]

lform/urls.py
from django.conf import settings

from django.conf.urls import url, include, static

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
blank_and_null = {'blank': True, 'null': True}


class Item(models.Model):
    title = models.CharField(verbose_name=_('title'), max_length=255)
    info = models.TextField(verbose_name=_('info'))
    image = models.ImageField(verbose_name=_('image'),
        upload_to='images',
        **blank_and_null)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')

apps/core/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy, reverse, resolve
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView, TemplateView, UpdateView, DetailView
from django import forms

from . import models as core_models

import logging

log = logging.getLogger('views')


class IndexView(TemplateView):
    template_name = 'apps/core/index_view.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['item'] = core_models.Item.objects.first()

        return context


class SuccessView(TemplateView):
    template_name = 'apps/core/success_view.html'


# unbounded form
class Form1View(FormView):
    template_name = 'apps/core/form1_view.html'
    success_url = reverse_lazy('core:SuccessView')

    def get_form_class(self):
        class _Form(forms.Form):
            first_name = forms.CharField(label=_('first name'), required=True)
            last_name = forms.DateField(label=_('last name'), required=False)
            choice = forms.ChoiceField(label=_('choice'),
                choices=((1, _('val1')), (2, _('val2'))))
            choice_models = forms.ModelChoiceField(
                queryset=core_models.Item.objects.all())
            image = forms.ImageField(label=_('image'), required=False)

        return _Form

    def form_valid(self, form):
        log.debug('form valid')

        return super(Form1View, self).form_valid(form)


class Form1(forms.Form):
    first_name = forms.CharField(label=_('first name'), required=True)
    last_name = forms.DateField(label=_('last name'), required=False)
    choice = forms.ChoiceField(label=_('choice'),
        choices=((1, _('val1')), (2, _('val2'))))
    choice_models = forms.ModelChoiceField(
        queryset=core_models.Item.objects.all())
    image = forms.ImageField(label=_('image'), required=False)


def form1_view(request, *args, **kwargs):
    form = Form1(data=request.POST or None, files=request.FILES or None)

    if form.is_valid():
        return redirect('core:SuccessView')

    return render(request, 'apps/core/form1_view.html', {'form': form})


# bounded forms cbv
class ItemDetailView(DetailView):
    model = core_models.Item
    template_name = 'apps/core/item_detail_view.html'


class ItemCreateUpdateView(UpdateView):
    model = core_models.Item
    template_name = 'apps/core/item_create_update_view.html'

    def get_success_url(self):
        return reverse('core:ItemDetailView', kwargs={'pk': self.object.pk})

    def get_object(self, queryset=None):
        return self.model.objects.filter(pk=self.kwargs.get('pk')).first()

    def get_form_class(self):
        self_model = self.model

        class _Form(forms.ModelForm):
            class Meta:
                model = self_model
                fields = '__all__'  # TODO: remove ! only for test!!!

        return _Form

    def get_context_data(self, **kwargs):
        context = super(ItemCreateUpdateView, self).get_context_data(**kwargs)
        context['curr_view'] = resolve(self.request.path)
        return context


# bounded forms fbv
def item_create_update_view(request, *args, **kwargs):
    class _Form(forms.ModelForm):
        class Meta:
            model = core_models.Item
            fields = '__all__'

    instance = core_models.Item.objects.filter(pk=kwargs.get('pk')).first()

    form = _Form(instance=instance, data=request.POST or None)
    if form.is_valid():
        instance = form.save()
        return redirect('core:ItemDetailView', pk=instance.pk)
    return render(request, 'apps/core/item_create_update_view.html', {
        'form': form
    })


# ajax
class ItemCreateUpdateViewAjax(ItemCreateUpdateView):
    template_name = 'apps/core/item_create_update_view_ajax.html'

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response({'success': True})

apps/core/templates/apps/core/form1_view.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<form action="." method="post">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  
  <button type="submit">submit</button>
</form>

</body>
</html>

apps/core/templates/apps/core/index_view.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<h1>Work with forms</h1>
<ul>
  <li><a href="{% url 'core:Form1View' %}">cbv form</a></li>
  <li><a href="{% url 'core:form1_view' %}">fbv form</a></li>
  <li><a href="{% url 'core:ItemCreateView' %}">cbv create model form</a></li>
  <li><a href="{% url 'core:item_create_view' %}">fbv create model form</a></li>


  {% if item %}
    <li><a href="{% url 'core:ItemUpdateView' pk=item.pk %}">cbv update model form</a></li>
    <li><a href="{% url 'core:item_update_view' pk=item.pk %}">fbv update model form</a></li>
  {% endif %}
</ul>

</body>
</html>

apps/core/templates/apps/core/item_create_update_view.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

<h1>{% if object %}Update{% else %}Create{% endif %}</h1>
<div>{% if curr_view.view_name == 'core:ItemCreateView' or curr_view.view_name == 'core:ItemUpdateView' %}CBV{% else %}
  FBV{% endif %} example
</div>
<div data-ctl="ajax-content">
  {% include 'apps/core/item_create_update_view_ajax.html' %}
</div>

<button type="button" data-ctl="btn">ajax send</button>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.4/js.cookie.js"></script>

<script>
    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
          // Only send the token to relative URLs i.e. locally.
          xhr.setRequestHeader('X-CSRFToken', Cookies.get('csrftoken'));
        }
      }
    });

    $(function () {
      $('[data-ctl="btn"]').on('click', function () {
        $.ajax({
          url: '{% if object %}{% url 'core:ItemUpdateViewAjax' pk=object.pk %}{% else %}{% url 'core:ItemCreateViewAjax' %}{% endif %}',
          data: new FormData($('[data-ctl="ajax-form"]').get(0)),
          cache: false,
          contentType: false,
          processData: false,
          type: 'POST',
          success: function (data) {
            $('[data-ctl="ajax-content"]').html(data)
          }
        })
      })
    })

</script>

</body>
</html>

apps/core/templates/apps/core/item_create_update_view_ajax.html
{% if success %}
  <h2>Success!!</h2>
{% else %}
  <form action="" data-ctl="ajax-form" method="post" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit">submit</button>
  </form>
{% endif %}

apps/core/templates/apps/core/item_detail_view.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<a href="{% url 'core:IndexView' %}">go home</a>
<h1>{{ object.title }}</h1>
<h2>{{ object.info }}</h2>

<h3><a href="{% url 'core:ItemUpdateView' pk=object.pk %}">edit cbv</a></h3>
<h3><a href="{% url 'core:item_update_view' pk=object.pk %}">edit fbv</a></h3>
</body>
</html>

apps/core/templates/apps/core/success_view.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<a href="{% url 'core:IndexView' %}">go home</a>
<h1>Success!</h1>
</body>
</html>